### ISSUE TITLE
How can I help the jazzzband roadie?

### ISSUE THREAD

**Issue by mattseymour** [jazzband/help#281] opened 2022-04-11 11:13 UTC
Hey @jezdez, Really appreciate what you do through jazzband and to see the continual growth of new projects. I was wondering what I can do to help you out with the project. I see a lot of requests coming in to various project (some by me).

It looks like a lot of the requests are for help, support and maintenance access, as well as new projects wanting to join. Can I do something to help you, or where can I add the most value to the project going forwards.

Thanks, 
Matt

**Comment by valberg** [comment] 2022-04-25 14:06
I would also like to help in any way possible!

**Comment by jezdez** [comment] 2022-12-12 08:51
Closing as duplicate of #196.

**Closed by jezdez** 2022-12-12 08:51 UTC
Labels: question
